- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/request/ProdutoForm.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/ProdutoDTO.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Produto.java
- src/main/java/com/bootcamp_w3_g3/repository/ProdutoRepository.java
- src/main/java/com/bootcamp_w3_g3/service/ProdutoService.java
- src/test/java/com/bootcamp_w3_g3/controller/LoteIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/OrdemEntradaIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/service/LoteUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/ProdutoServiceUnitTest.java
> produto controller refatorada

- src/main/java/com/bootcamp_w3_g3/controller/ArmazemController.java
- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/controller/RepresentanteController.java
- src/main/java/com/bootcamp_w3_g3/controller/SetorController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/request/ArmazemForm.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/request/SetorForm.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/ArmazemDTO.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/SetorDTO.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Armazem.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Representante.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Setor.java
- src/main/java/com/bootcamp_w3_g3/service/ArmazemService.java
- src/main/java/com/bootcamp_w3_g3/service/RepresentanteService.java
- src/main/java/com/bootcamp_w3_g3/service/SetorService.java
- src/main/resources/application.properties
- src/test/java/com/bootcamp_w3_g3/controller/ArmazemIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/RepresentanteIntTest.java
- src/test/java/com/bootcamp_w3_g3/service/ArmazemServiceUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/SetorUnitTest.java
> Teste manual e de integração finalizado

- src/main/java/com/bootcamp_w3_g3/repository/CompradorRepository.java
> Comprador Repository

- .gitignore
- src/main/java/com/bootcamp_w3_g3/config/WebSecurity.java
- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/model/entity/StatusCompra.java
- src/main/java/com/bootcamp_w3_g3/model/entity/TipoProduto.java
- src/main/java/com/bootcamp_w3_g3/repository/ProdutoRepository.java
- src/main/java/com/bootcamp_w3_g3/service/ProdutoService.java
- src/test/java/com/bootcamp_w3_g3/controller/OrdemEntradaIntegrationTest.java
Atualizacao do arquivo gitignore
refatoracao das enum
buscar produtos por categoria
> Endpoint listar produtos por categoria

- src/main/java/com/bootcamp_w3_g3/config/WebSecurity.java
- src/main/java/com/bootcamp_w3_g3/controller/CarrinhoController.java
- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/request/ProdutoForm.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Produto.java
- src/main/java/com/bootcamp_w3_g3/service/CarrinhoService.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
> requisito 2 finalizado

- src/test/java/com/bootcamp_w3_g3/service/CompradorUnitTest.java
CompradorUnitTest
obterCompradorTest() created and OK.
> CompradorUnitTest

- src/main/java/com/bootcamp_w3_g3/service/CarrinhoService.java
- src/test/java/com/bootcamp_w3_g3/service/CarrinhoUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/ProdutoServiceUnitTest.java
Criado métodos de unit test, criados para atender aos métodos do requisito 2. 
Alex Cruz
> CarrinhoUnitTest métodos que atendem ao requisito 2.

- src/main/java/com/bootcamp_w3_g3/controller/AutenticadorController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/request/SetorForm.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/SetorDTO.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Setor.java
- src/main/java/com/bootcamp_w3_g3/service/CarrinhoService.java
- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/main/java/com/bootcamp_w3_g3/service/OrdemDeEntradaService.java
- src/test/java/com/bootcamp_w3_g3/controller/OrdemEntradaIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/SetorIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/service/OrdemDeEntradaUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/SetorUnitTest.java
> teste de integracao produto 100%

- src/main/java/com/bootcamp_w3_g3/service/CarrinhoService.java
- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/main/java/com/bootcamp_w3_g3/service/OrdemDeEntradaService.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/service/OrdemDeEntradaUnitTest.java
**_LoteService_**: necessidade dum construtor com loteRepository adicionado;
**_OrdemDeEntradaService_**: necessidade de método obter para teste unitário;
**_OrdemDeEntradaServiceTest_**: conseguir passar, aplicação de condicional, criação de mocks necessários;
**_ProdutoIntegrationTest_**: Remoção de produto.setNumeroDoLote, já que este método foi "depreciado" nas vossas atualizações.
> Enfim... Ordertest + mudanças fundamentais.

- pom.xml
1 - Entrar na guia do MAVEN -> botão de reload, compile, clean, ... tudo mais.
2 -Run -> Edit CONFIGURATIONS
....code coverage....
-> modify
* Specify alternative code coverage runner
(selecionar jacoco)
> Apenas o POM com JaCoCo

- src/main/java/com/bootcamp_w3_g3/controller/SetorController.java
- src/main/java/com/bootcamp_w3_g3/model/entity/OrdemDeEntrada.java
- src/main/java/com/bootcamp_w3_g3/repository/SetorRepository.java
- src/main/java/com/bootcamp_w3_g3/service/SetorService.java
- src/test/java/com/bootcamp_w3_g3/controller/ArmazemIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/LoteIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/OrdemEntradaIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/RepresentanteIntTest.java
- src/test/java/com/bootcamp_w3_g3/controller/SetorIntegrationTest.java
> Integration tests refactored 

- src/main/java/com/bootcamp_w3_g3/service/SetorService.java
- src/test/java/com/bootcamp_w3_g3/service/SetorUnitTest.java
Refatorado obterArmazemTest(), devido a necessidade efetuar Mock da armazemService e então criar injecão de dependência.
Alex Cruz
> Refatorado obterArmazemTest(), devido a necessidade efetuar Mock 

- src/main/java/com/bootcamp_w3_g3/controller/ItensController.java
- src/main/java/com/bootcamp_w3_g3/repository/ItensRepository.java
- src/main/java/com/bootcamp_w3_g3/service/ItensService.java
- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/main/java/com/bootcamp_w3_g3/service/ProdutoService.java
- src/main/java/com/bootcamp_w3_g3/service/VendedorService.java
- src/test/java/com/bootcamp_w3_g3/controller/ItensIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/VendedorIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/service/ItensUnitTest.java
> new integration tests

- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/main/java/com/bootcamp_w3_g3/service/VendedorService.java
- src/test/java/com/bootcamp_w3_g3/service/LoteUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/VendedorServiceUnitTest.java
Refatorado salvaLoteTest() e atualizaVendedorTest().
Alex Cruz
> Refeatorando teste unitários salvarLoteTest() e atualizaVendedorTest()

- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/ArmazemDTO.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/LoteDTO.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/responseReq3/ArmazemDto.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/responseReq3/RepresentanteDto.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/responseReq3/SetorDto.java
- src/main/java/com/bootcamp_w3_g3/service/CarrinhoService.java
- src/main/java/com/bootcamp_w3_g3/service/ProdutoService.java
> endpoint para consultar um produto em stock 

- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
> LoteService alterado.

- src/main/java/com/bootcamp_w3_g3/model/dtos/request/CarrinhoForm.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Carrinho.java
- src/main/java/com/bootcamp_w3_g3/service/ArmazemService.java
- src/main/java/com/bootcamp_w3_g3/service/CarrinhoService.java
- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/main/java/com/bootcamp_w3_g3/service/OrdemDeEntradaService.java
- src/main/java/com/bootcamp_w3_g3/service/ProdutoService.java
- src/main/java/com/bootcamp_w3_g3/service/SetorService.java
- src/main/java/com/bootcamp_w3_g3/service/VendedorService.java
- src/test/java/com/bootcamp_w3_g3/service/CarrinhoUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/LoteUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/OrdemDeEntradaUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/ProdutoServiceUnitTest.java
> refatoração no metodo para registrar um compra

- src/test/java/com/bootcamp_w3_g3/controller/CompradorIntegrationTest.java
CompradorIntegrationTest created with success.
> CompradorIntegrationTest

- src/main/java/com/bootcamp_w3_g3/advisor/handler/DeleteException.java
- src/main/java/com/bootcamp_w3_g3/advisor/handler/EntityNotFoundExceptionHandler.java
- src/main/java/com/bootcamp_w3_g3/controller/RepresentanteController.java
- src/main/java/com/bootcamp_w3_g3/service/RepresentanteService.java
- src/test/java/com/bootcamp_w3_g3/controller/RepresentanteIntTest.java
* Criação de DeleteException e sua colocação no handler, adicionado ao EntityNotFoundExceptionHandler;
* RepresentanteIntTest com métodos para listagem e dual de deleção (para representante não persistido);
(consequentemente!):
* RepresentanteController sem exceções capturadas em try-catch;
* RepresentanteService com método apagar revertido.
> *Help do Kenyo*

- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/requisito4/DTOArmazem.java
- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/test/java/com/bootcamp_w3_g3/controller/RepresentanteIntTest.java
DTOArmazem criado.
RepresentanteIntTest corrigido.
Requisito 4 finalizado
> Requisito 4 finalizado

- src/test/java/com/bootcamp_w3_g3/service/LoteUnitTest.java
> teste unitário 

- src/main/java/com/bootcamp_w3_g3/model/dtos/response/requisito5/DTOLote.java
> DTOLote (requisito 5)

- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
Criado método retornaLotesPorCategoria() referente ao requisito 5.
> segundo endPoint do requisito 5

- src/main/java/com/bootcamp_w3_g3/service/LoteService.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
listar todos os lotes do setor do produto ordenados pela data de validade.
> Integration test

- src/main/java/com/bootcamp_w3_g3/model/dtos/response/requisito5/DTOLote.java
- src/test/java/com/bootcamp_w3_g3/service/LoteUnitTest.java
DTO lote: método de conversão necessário criado, LoteUnitTest agora comm método de Listagem do primeiro endmpoint. Cobertura subiu de 76% para 85%.
> DTO lote (converter) TU do 1º Endpoint

- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/service/LoteUnitTest.java
Teste integração do 2o endpoint - Requisito 5
Adicionado autor Hugo no LoteUnitTest.
> Teste integração do 2o endpoint - Requisito 5

- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
Correção ProdutoIntegrationTest
> Correção ProdutoIntegrationTest

- src/test/java/com/bootcamp_w3_g3/controller/RepresentanteIntTest.java
Método listartodosRepresentantes() do RepresentanteIntTest
> Método listartodosRepresentantes() do RepresentanteIntTest

- src/test/java/com/bootcamp_w3_g3/controller/CarrinhoIntegrationTest.java
Create classe CarrinhoIntegrationTest juntamento com o método deveRegistrarUmCarrinho.
Alex Cruz
> Criado classe CarrinhioIntegrationTest

- README.md
Criando Readme com as considerações iniciais.
> Create: README.md 

- README.md
- src/main/java/com/bootcamp_w3_g3/controller/CarrinhoController.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/request/CompradorForm.java
- src/main/java/com/bootcamp_w3_g3/model/dtos/response/ProdutoDTO.java
- src/main/java/com/bootcamp_w3_g3/repository/CompradorRepository.java
- src/main/java/com/bootcamp_w3_g3/repository/RepresentanteRepository.java
- src/main/java/com/bootcamp_w3_g3/repository/VendedorRepository.java
- src/main/java/com/bootcamp_w3_g3/service/CompradorService.java
- src/main/java/com/bootcamp_w3_g3/service/RepresentanteService.java
- src/main/java/com/bootcamp_w3_g3/service/VendedorService.java
- src/test/java/com/bootcamp_w3_g3/controller/ArmazemIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/CarrinhoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/CompradorIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/LoteIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/OrdemEntradaIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/ProdutoIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/RepresentanteIntTest.java
- src/test/java/com/bootcamp_w3_g3/controller/SetorIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/controller/VendedorIntegrationTest.java
- src/test/java/com/bootcamp_w3_g3/service/ArmazemServiceUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/CompradorUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/RepresentanteServiceUnitTest.java
- src/test/java/com/bootcamp_w3_g3/service/VendedorServiceUnitTest.java
Subindo as seguintes alterações:
> Criação das validações de campos.

- pom.xml
- src/main/java/com/bootcamp_w3_g3/config/SwaggerConfig.java
- src/main/java/com/bootcamp_w3_g3/controller/ArmazemController.java
- src/main/java/com/bootcamp_w3_g3/controller/CompradorController.java
- src/main/java/com/bootcamp_w3_g3/controller/LoteController.java
- src/main/java/com/bootcamp_w3_g3/controller/ProdutoController.java
- src/main/java/com/bootcamp_w3_g3/controller/RepresentanteController.java
- src/main/java/com/bootcamp_w3_g3/controller/SetorController.java
- src/main/java/com/bootcamp_w3_g3/controller/VendedorController.java
- src/main/java/com/bootcamp_w3_g3/model/entity/Representante.java
> Documentação Swagger
